# Generated by Django 3.2.5 on 2021-07-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='cat',
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='main_app.cat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='main_app.owner')),
            ],
        ),
    ]
